### ISSUE TITLE
Unsupported Dart version: e4a09dbf2bb120fe4674e0576617a0dc

### ISSUE THREAD

**Issue by microxpgg** [rscloura/Doldrums#9]
I have no idea which version of dart this is...

**Comment by rscloura** [comment]
This is Dart version 2.13, the newest addition to the engine. Doldrums still doesn't support this version (it will very soon!).

**Comment by sticksen** [comment]
Looking forward to support of e4a09dbf2bb120fe4674e0576617a0dc, too!

**Comment by it4chi409** [comment]
> @rscloura Is there any way to assist in getting this up and running?
I can help in this as well, I actually tried following your blog to see if I could get 2.13 working but was unable to figure the whole thing out myself

**Comment by anasmadrhar** [comment]
Hi @rscloura ,
I've been trying to create v2_13 support using what you mentioned. now I'm stuck because im getting some weird cid values and this error:
`ValueError: -7166 is not a valid ClassId`
any idea on how to fix this?

**Comment by hpp0hpp** [comment]
> * Verify that the class IDs in `ClassId.py` match those in Dart's source (`runtime/vm/class_id.h`), and update accordingly.

@rscloura Hi , runtime/vm/class_id.h didn't indicate the classid value, how could I update the new classid's value and update?

**Comment by ReactJSTeams** [comment]
Hi @rscloura,
I am working on the version 2.13.x (e4a09dbf2bb120fe4674e0576617a0dc) currently. I fixed few things and add a deserializer for String().
https://github.com/dart-lang/sdk/blob/2.13.0/runtime/vm/clustered_snapshot.cc
// line 7109
`#if !defined(DART_COMPRESSED_POINTERS)
  if (Snapshot::IncludesCode(kind_)) {
    switch (cid) {
      case kPcDescriptorsCid:
      case kCodeSourceMapCid:
      case kCompressedStackMapsCid:
        return new (Z) RODataDeserializationCluster(!is_non_root_unit_, cid);
      case kOneByteStringCid:
      case kTwoByteStringCid:
        if (!is_non_root_unit_) {
          return new (Z) RODataDeserializationCluster(!is_non_root_unit_, cid);
        }
        break;
      case kStringCid:
        RELEASE_ASSERT(!is_non_root_unit_);
        return new (Z) RODataDeserializationCluster(!is_non_root_unit_, cid);
    }
  }
#endif`
But there is few problems I still can not fix yet.
I got a error message with the ObjectPool Deserializer(_readFill function).
`INFO:LibraryDeserializer fill stage at offset: 922641
INFO:WeakSerializationReferenceDeserializer fill stage at offset: 953837
INFO:CodeDeserializer fill stage at offset: 953837
INFO:ObjectPoolDeserializer fill stage at offset: 1374752
INFO:encodedBit: 130 decodeBit: 2
INFO:encodedBit: 129 decodeBit: 1
INFO:encodedBit: 98 decodeBit: 98
Traceback (most recent call last):
  File "\src\main.py", line 77, in <module>
    isolate = parseELF(args.file)
  File "\src\main.py", line 29, in parseELF
    isolate = Snapshot(blobs[2], offsets[2], blobs[3], offsets[3], vm)
  File "\v2_13\Snapshot.py", line 47, in __init__
    cluster.readFill(self, False)
  File "\v2_13\Cluster.py", line 19, in readFill
    self._readFill(snapshot, isCanonical)
  File "\v2_13\Cluster.py", line 540, in _readFill
    raise Exception('No type associated to decoded type bits')
Exception: No type associated to decoded type bits`

here is the source code: 
https://github.com/ReactJSTeams/Doldrums/tree/v213/src/v2_13

**Comment by ReactJSTeams** [comment]
> > Hmm... That's odd. Is it a "normal looking" value (i.e.: between 1 and 200)? If that's the case, make sure you are looking at the correct version of `class_id.h`. Dart changes very frequently the `enum`. If not the case, then there's probably an error in the parsing logic until that point.
> 
> Hi, how to know the value of cID from class_id.h to update the classID.py? I'm interested to learn about this.
> 
> ![Screen Shot 2022-03-16 at 03 01 42](https://user-images.githubusercontent.com/6284204/158461526-3e7fb3b6-39ef-4190-87db-58539289f8c6.png)
> 
> Edit: I got it how it work. It's incremental number from illegal = 0. Now figuring out how to build cluster.py
> 
> In 2.15+ there is no clustered_snapshot.cc https://github.com/dart-lang/sdk/blob/2.15.0/runtime/vm/clustered_snapshot.cc

Check this: https://github.com/dart-lang/sdk/blob/2.15.0/runtime/vm/app_snapshot.cc

**Comment by aancw** [comment]
> > > Hmm... That's odd. Is it a "normal looking" value (i.e.: between 1 and 200)? If that's the case, make sure you are looking at the correct version of `class_id.h`. Dart changes very frequently the `enum`. If not the case, then there's probably an error in the parsing logic until that point.
> > 
> > Hi, how to know the value of cID from class_id.h to update the classID.py? I'm interested to learn about this.
> > 
> > ![Screen Shot 2022-03-16 at 03 01 42](https://user-images.githubusercontent.com/6284204/158461526-3e7fb3b6-39ef-4190-87db-58539289f8c6.png)
> > 
> > Edit: I got it how it work. It's incremental number from illegal = 0. Now figuring out how to build cluster.py
> > 
> > In 2.15+ there is no clustered_snapshot.cc https://github.com/dart-lang/sdk/blob/2.15.0/runtime/vm/clustered_snapshot.cc
> 
> Check this: https://github.com/dart-lang/sdk/blob/2.15.0/runtime/vm/app_snapshot.cc

Let me check it. Hey, how do you make function in cluster.py? I'm reading Deserialization function in the .c file but still don't know.

**Comment by rscloura** [comment]
The implementations in `cluster.py` very closely follow the `DeserializationCluster`s in the linked sources. It's essentially rewriting the original C code in Python :)

**Comment by ReactJSTeams** [comment]
> INFO:encodedBit

Hi @rscloura, I have no idea why i still get wrong encoded bits start from third bit...

**Comment by aancw** [comment]
> > INFO:encodedBit
> 
> Hi @rscloura, I have no idea why i still get wrong encoded bits start from third bit...

From your error exception, it's because of ObjectPoolDeserializer. Mistmatch entry data?

![Screen Shot 2022-03-22 at 15 27 50](https://user-images.githubusercontent.com/6284204/159438944-173736aa-40ee-40bb-971d-0742a49ac62b.png)

**Comment by cryptax** [comment]
hi @ReactJSTeams I tried to use your branch but unfortunately it raised an exception in `src/v2_13/Utils.py`:

```
raise Exception('Expected boolean, but received non-boolean value while reading at stream offset: ' + str(stream.tell()))
Exception: Expected boolean, but received non-boolean value while reading at stream offset: 961687
```

the call stack is:

- `isolate = parseELF(args.file)`
- `isolate = Snapshot(blobs[2], offsets[2], blobs[3], offsets[3], vm)`
- `cluster.readFill(self, False)`
- `self._readFill(snapshot, isCanonical)`
- `info['needsStacktrace'] = StreamUtils.readBool(snapshot.stream)`
- `raise Exception('Expected boolean, but received non-boolean value while reading..`

It occurs in ExceptionHandlersDeserializer

```
INFO:CodeDeserializer fill stage at offset: 639936
INFO:ObjectPoolDeserializer fill stage at offset: 961681
INFO:PcDescriptorsDeserializer fill stage at offset: 961682
INFO:CompressedStackMapsDeserializer fill stage at offset: 961682
INFO:ExceptionHandlersDeserializer fill stage at offset: 961682
Traceback (most recent call last):
```

**Comment by cryptax** [comment]
I managed to go beyond that Exception by fixing this in the code:

```python
					# Original code has read int8
					info['needsStacktrace'] = StreamUtils.readInt(snapshot.stream,8)
					info['hasCatchAll'] = StreamUtils.readInt(snapshot.stream,8)
					info['isGenerated'] = StreamUtils.readInt(snapshot.stream,8)
```

but now it looks like it stalls on `b = int.from_bytes(x, 'big', signed=False)` from `./Doldrums/src/v2_13/Utils.py`

```
self._readFill(snapshot, isCanonical)
info['handlerPcOffset'] = StreamUtils.readUnsigned(snapshot.stream, 32)
return StreamUtils.read(stream, StreamUtils.kEndUnsignedByteMarker, math.ceil(size / 7))
```
